on: [pull_request, push]
name: CI
jobs:
  run-ci:
    runs-on: [self-hosted, linux, x64]
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: composer install --no-scripts

      - name: Run Testsuite
        run: composer test

      - name: Run Linting
        run: composer lint

      - name: Run Static Analysis
        run: composer analyse