on: [pull_request, push]
name: CI
jobs:
  run-ci:
    strategy:
      fail-fast: true
      matrix:
        php: [ "8.2" ]

    runs-on: [self-hosted, linux, x64]
    name: PHP@${{ matrix.php }}

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Testsuite
        run: composer run-script test

      - name: Run Linting
        run: composer run-script lint

      - name: Run Static Analysis
        run: composer run-script analyse